#!/bin/sh

export REDLIB_PORT=$PORT
export REDLIB_DEFAULT_WIDE=on
export REDLIB_DEFAULT_USE_HLS=on
export REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION=on
export REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION=on
export REDLIB_DEFAULT_COMMENT_SORT=top
export REDLIB_DEFAULT_SHOW_NSFW=on
export REDLIB_DEFAULT_POST_SORT=top
export REDLIB_DEFAULT_THEME=dracula

./redlib
